<a href="https://colab.research.google.com/github/Adarsha9845/Possible-Combination-of-Generator-Outage/blob/main/Possible_Combination_of_Generation_unit_Outage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
capOut1 = np.array([0, 5, 10, 15])
capOut2 = np.array([0, 5, 10, 15, 20])
prob1 = np.array([0.96, 0.03, 0.01, 0.08])
prob2 = np.array([0.94, 0.04, 0.01, 0.01, 0.08])
print(capOut1, capOut2, prob1, prob2)

[ 0  5 10 15] [ 0  5 10 15 20] [0.96 0.03 0.01 0.08] [0.94 0.04 0.01 0.01 0.08]


In [3]:
capOut1.shape

(4,)

In [4]:
def sumOperation(array1, array2):
  output = []

  for num in array2:
      temp = []
      for element in array1:
          temp.append(element + num)
      output.append(temp)

  # Print the output array
  for row in output:
      print(" ".join(map(str, row)))
  return output

In [5]:
def multiplyOperation(array1, array2):
  output = []

  for num in array2:
      temp = []
      for element in array1:
          temp.append(element * num)
      output.append(temp)

  # Print the output array
  for row in output:
      print(" ".join(map(str, row)))
  return output

In [6]:
output2 = multiplyOperation(prob1, prob2)
print(np.array(output2))

0.9023999999999999 0.028199999999999996 0.0094 0.0752
0.0384 0.0012 0.0004 0.0032
0.0096 0.0003 0.0001 0.0008
0.0096 0.0003 0.0001 0.0008
0.0768 0.0024 0.0008 0.0064
[[9.024e-01 2.820e-02 9.400e-03 7.520e-02]
 [3.840e-02 1.200e-03 4.000e-04 3.200e-03]
 [9.600e-03 3.000e-04 1.000e-04 8.000e-04]
 [9.600e-03 3.000e-04 1.000e-04 8.000e-04]
 [7.680e-02 2.400e-03 8.000e-04 6.400e-03]]


In [10]:
flattenOutput2 = np.array(output2).reshape((-1, 1))
print(flattenOutput2)

[[9.024e-01]
 [2.820e-02]
 [9.400e-03]
 [7.520e-02]
 [3.840e-02]
 [1.200e-03]
 [4.000e-04]
 [3.200e-03]
 [9.600e-03]
 [3.000e-04]
 [1.000e-04]
 [8.000e-04]
 [9.600e-03]
 [3.000e-04]
 [1.000e-04]
 [8.000e-04]
 [7.680e-02]
 [2.400e-03]
 [8.000e-04]
 [6.400e-03]]


In [8]:
output1 = sumOperation(capOut1, capOut2)
print(output1)

0 5 10 15
5 10 15 20
10 15 20 25
15 20 25 30
20 25 30 35
[[0, 5, 10, 15], [5, 10, 15, 20], [10, 15, 20, 25], [15, 20, 25, 30], [20, 25, 30, 35]]


In [9]:
flattenOutput1 = np.array(output1).reshape((-1, 1))
print(flattenOutput1)

[[ 0]
 [ 5]
 [10]
 [15]
 [ 5]
 [10]
 [15]
 [20]
 [10]
 [15]
 [20]
 [25]
 [15]
 [20]
 [25]
 [30]
 [20]
 [25]
 [30]
 [35]]


In [19]:
def findUnique(Array1, Array2):
  averaged_dict = {}

  # Iterate over Array1 and Array2 simultaneously
  for val1, val2 in zip(Array1, Array2):
      # Convert val1 to a scalar
      val1_scalar = val1.item()
      # If val1 already exists in the dictionary, append val2 to its list
      if val1_scalar in averaged_dict:
          averaged_dict[val1_scalar].append(val2.item())
      # If val1 is encountered for the first time, create a new list with val2
      else:
          averaged_dict[val1_scalar] = [val2.item()]

  # Initialize arrays to store averaged values
  averaged_values = np.zeros_like(Array1, dtype=float)

  # Iterate over the dictionary items to calculate the average for each unique value in Array1
  for key, value in averaged_dict.items():
      averaged_values[np.where(Array1 == key)] = np.mean(value)

  # # Print the output array
  # for val1, val2 in zip(Array1, averaged_values):
  #     print(f"{val1.item()}  {val2:.3e}")
  return averaged_values,

In [20]:
uniqueValues = findUnique(flattenOutput1, flattenOutput2)

In [24]:
# [uniqueValues, flattenOutput1]

[array([[9.02400000e-01],
        [3.33000000e-02],
        [6.73333333e-03],
        [2.13750000e-02],
        [3.33000000e-02],
        [6.73333333e-03],
        [2.13750000e-02],
        [2.01000000e-02],
        [6.73333333e-03],
        [2.13750000e-02],
        [2.01000000e-02],
        [1.10000000e-03],
        [2.13750000e-02],
        [2.01000000e-02],
        [1.10000000e-03],
        [8.00000000e-04],
        [2.01000000e-02],
        [1.10000000e-03],
        [8.00000000e-04],
        [6.40000000e-03]]),
 array([[ 0],
        [ 5],
        [10],
        [15],
        [ 5],
        [10],
        [15],
        [20],
        [10],
        [15],
        [20],
        [25],
        [15],
        [20],
        [25],
        [30],
        [20],
        [25],
        [30],
        [35]])]

In [33]:
def mergeArray(Array1, Array2):
  # Merge the arrays
  merged_array = np.concatenate((Array1, Array2), axis=1)

  # Eliminate duplicate rows
  unique_rows = np.unique(merged_array, axis=0)

  print(unique_rows)

In [36]:
finalArray = mergeArray(flattenOutput1, uniqueValues)

[[0.00000000e+00 9.02400000e-01]
 [5.00000000e+00 3.33000000e-02]
 [1.00000000e+01 6.73333333e-03]
 [1.50000000e+01 2.13750000e-02]
 [2.00000000e+01 2.01000000e-02]
 [2.50000000e+01 1.10000000e-03]
 [3.00000000e+01 8.00000000e-04]
 [3.50000000e+01 6.40000000e-03]]


In [30]:
# a = np.array([[1], [2], [3]])
# b = np.array([[2], [3], [4]])
# merged_array = np.concatenate((a, b), axis=1)
# merged_array

array([[1, 2],
       [2, 3],
       [3, 4]])